name: Python_Crawler

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  job1:
    name: windows-pyinstaller
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
          architecture: x64

      - name: Install dependecies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: List dependecies
        run: |
          pip list

      - name: Test pyinstaller
        run: |
          pyinstaller `
            --onefile -c pyinstaller_clean.py

      - name: Test with pytest
        run: |
          python -m pytest tests

      - name: Upload pytest test results
        uses: actions/upload-artifact@v2
        with:
          name: Python_Crawler_pytest_results-windows
          path: |
            htmlcov
            tests/result

      - name: Upload dist artifact
        uses: actions/upload-artifact@v2
        with:
          name: python_crawler-windows
          path: dist

  job2:
    name: linux-pyinstaller
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
          architecture: x64

      - name: Install dependecies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test dependecies
        run: |
          pip list

      - name: Test pyinstaller
        run: |
          pyinstaller \
            --onefile pyinstaller_clean.py

      - name: Test pyinstaller_clean
        run: |
          python pyinstaller_clean.py

      - name: Test config
        run: |
          python ./crawler/config.py

      - name: Upload dist artifact
        uses: actions/upload-artifact@v2
        with:
          name: python_crawler-linux
          path: dist
